import { Inter, Lato } from "next/font/google";
import "./globals.css";
import ITMakeoversNav from "@/components/ITMakeoversNav";

//create lato font
const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const links = [
    {
      name: "Wykształcenie",
      link: "#poznaj",
    },
    {
      name: "Doświadczenie",
      link: "#korzysci",
    },
    {
      name: "Projekty",
      link: "/#mapa-inwestycji",
    },
    {
      name: "O mnie",
      link: "#o-nas",
    },
    
  ];

  return (
    <html lang="en">
      <body className={lato.className}>
        <ITMakeoversNav links={links} />
        {children}
      </body>
    </html>
  );
}
